#!/usr/bin/env bash
set -euo pipefail
# shellcheck source=SCRIPTDIR/../lib/common.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"

step "Setting up the GitHub SSH key"

key="$HOME/.ssh/id-github"

if [ -f "$key" ]; then
	skip "$key"
else
	install -d -m 0700 "$HOME/.ssh"
	ssh-keygen -t ed25519 -C "$(git config --global user.email || echo "$USER@$(hostname)")" -f "$key" -N ""
	eval "$(ssh-agent -s)" >/dev/null
	ssh-add "$key"

	if have gh && gh auth status >/dev/null 2>&1; then
		read -r -p "    Title for the new GitHub SSH key: " title
		gh ssh-key add "${key}.pub" --title "${title:-$(hostname)}"
		gh ssh-key add "${key}.pub" --title "${title:-$(hostname)} (signing)" --type signing
	else
		warn "gh is not authenticated. Run 'gh auth login', then add the key:"
		warn "  gh ssh-key add ${key}.pub --title \"\$(hostname)\""
	fi
fi

# The Host alias used by .gitconfig's insteadOf rewrite.
if [ ! -f "$HOME/.ssh/config" ]; then
	info "Writing ~/.ssh/config"
	install -m 0600 "$DOTFILES_ROOT/config/ssh/config" "$HOME/.ssh/config"
fi

# Allowed signers — what .gitconfig's gpg.ssh.allowedSignersFile points at.
#
# Git verifies SSH signatures against this file alone; it does not consult
# GitHub. Without it every commit fails verification locally, however well
# signed. Every signing key on the account is included, not just this
# machine's, so commits made elsewhere verify here too.
step "Writing ~/.ssh/allowed_signers"

signers="$HOME/.ssh/allowed_signers"
email="$(git config --get user.email || true)"

if [ -z "$email" ]; then
	warn "git user.email is unset; skipping allowed_signers"
	exit 0
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
	echo "# Generated by scripts/generate-ssh-key.sh — do not edit by hand."
	echo "# Regenerate after adding a signing key to your GitHub account."

	# This machine's key, so verification works offline and before `gh` is set up.
	if [ -f "${key}.pub" ]; then
		printf '%s namespaces="git" %s\n' "$email" "$(awk '{print $1, $2}' "${key}.pub")"
	fi

	# Every signing key registered on the account. Needs the
	# admin:ssh_signing_key scope: gh auth refresh -s admin:ssh_signing_key
	if have gh && gh auth status >/dev/null 2>&1; then
		gh api user/ssh_signing_keys --jq '.[].key' 2>/dev/null |
			while read -r keytype keydata _; do
				[ -n "${keydata:-}" ] || continue
				printf '%s namespaces="git" %s %s\n' "$email" "$keytype" "$keydata"
			done ||
			warn "Could not read signing keys from GitHub (needs the admin:ssh_signing_key scope)"
	fi
} >"$tmp"

# Drop duplicates: this machine's key is usually registered on the account too.
sort -u -k3,4 "$tmp" | grep -v '^#' >"$tmp.keys" || true
{
	grep '^#' "$tmp"
	cat "$tmp.keys"
} >"$signers"
rm -f "$tmp.keys"
chmod 0644 "$signers"

info "$(grep -vc '^#' "$signers") signing key(s) trusted for git"
